# Generated by Django 4.2.4 on 2023-08-16 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=30)),
                ("nachname", models.CharField(max_length=30)),
                ("geburtsdatum", models.DateField()),
                ("ort", models.CharField(max_length=30)),
                ("Adresszeile", models.CharField(max_length=50)),
                ("Hausnummer", models.CharField(default="", max_length=50)),
                ("Stadt", models.CharField(default="", max_length=50)),
                ("Postleitzahl", models.IntegerField()),
                (
                    "User",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Profile",
            },
        ),
    ]
