# Generated by Django 4.2.4 on 2023-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="nachname",
        ),
        migrations.RemoveField(
            model_name="user_profile",
            name="vorname",
        ),
        migrations.AddField(
            model_name="user_profile",
            name="telefon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Adresszeile",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Hausnummer",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Postleitzahl",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="Stadt",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="geburtsdatum",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="ort",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
