# Generated by Django 4.2.4 on 2023-08-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_profile_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_profile",
            old_name="User",
            new_name="user",
        ),
    ]
