# Generated by Django 4.2.4 on 2023-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_user_user_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="geburtsdatum",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
