# Generated by Django 4.2.4 on 2023-08-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_profile_geburtsdatum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_profile",
            name="ort",
        ),
    ]
