# Generated by Django 4.2.4 on 2023-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0002_auftrag_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="auftrag",
            name="Hausnummer",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="auftrag",
            name="Straße",
            field=models.CharField(default="", max_length=50),
        ),
    ]
