# Generated by Django 4.2.4 on 2023-08-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0004_rename_adresse_auftrag_adresszeile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auftrag",
            name="PDF_label",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="Auftrag_Pdf/"
            ),
        ),
    ]
