# Generated by Django 4.2.4 on 2023-08-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0006_alter_auftrag_handy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auftrag",
            old_name="User",
            new_name="user",
        ),
    ]
