# Generated by Django 4.2.4 on 2023-08-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0007_rename_user_auftrag_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auftrag",
            old_name="user",
            new_name="User",
        ),
    ]
