# Generated by Django 4.2.4 on 2023-08-16 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0009_alter_auftrag_geburtsdatum"),
    ]

    operations = [
        migrations.AddField(
            model_name="auftrag",
            name="Auftrag_status",
            field=models.CharField(
                choices=[("Processing", "Processing"), ("Complete", "Complete")],
                default="Processing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auftrag",
            name="Zeit",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
