# Generated by Django 4.2.4 on 2023-08-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0010_auftrag_auftrag_status_auftrag_zeit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auftrag",
            name="ort",
        ),
    ]
