# Generated by Django 4.2.4 on 2023-08-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0011_remove_auftrag_ort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auftrag",
            name="schaden",
        ),
    ]
