# Generated by Django 4.2.4 on 2023-08-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0013_remove_auftrag_pdf_label_auftrag_pdf_responseapi"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Auftrag_Pdf_ResponseApi",
            new_name="AuftragPdfResponseApi",
        ),
    ]
