# Generated by Django 4.2.4 on 2023-09-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0015_alter_auftragpdfresponseapi_auftrag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auftragpdfresponseapi",
            name="response",
            field=models.BinaryField(),
        ),
    ]
