# Generated by Django 4.2.4 on 2023-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0016_alter_auftragpdfresponseapi_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="auftrag",
            name="screen_protector_status",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no")],
                default="no",
                max_length=255,
                null=True,
            ),
        ),
    ]
