# Generated by Django 4.2.4 on 2023-10-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0017_auftrag_screen_protector_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auftrag",
            name="Auftrag_status",
            field=models.CharField(
                choices=[
                    ("New Order", "New Order"),
                    ("In Repair", "In Repair"),
                    ("Complete", "Complete"),
                ],
                default="New Order",
                max_length=20,
            ),
        ),
    ]
