# Generated by Django 4.2.4 on 2023-10-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0019_alter_auftrag_auftrag_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Marke Table",
            },
        ),
        migrations.CreateModel(
            name="ModelTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Model Table",
            },
        ),
        migrations.CreateModel(
            name="SchadensartTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Price", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Schadensart Table",
            },
        ),
    ]
