# Generated by Django 4.2.4 on 2023-10-22 05:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("benutzer", "0021_modeltable_marke_schadensarttable_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ausgeführter_Befehl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("vorname", models.CharField(max_length=30)),
                ("nachname", models.CharField(max_length=30)),
                (
                    "geburtsdatum",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("Adresszeile", models.CharField(max_length=50)),
                ("Hausnummer", models.CharField(default="", max_length=50)),
                ("Stadt", models.CharField(default="", max_length=50)),
                ("Postleitzahl", models.IntegerField()),
                ("handy", models.CharField(blank=True, max_length=30, null=True)),
                ("marke", models.CharField(max_length=30)),
                ("model", models.CharField(max_length=30)),
                ("Schadensart", models.CharField(max_length=30)),
                (
                    "screen_protector_status",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "yes"), ("no", "no")],
                        default="no",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("kosten", models.FloatField(blank=True, null=True)),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Auftrag_status",
                    models.CharField(
                        choices=[
                            ("New Order", "New Order"),
                            ("In Repair", "In Repair"),
                            ("Completed", "Completed"),
                        ],
                        default="New Order",
                        max_length=20,
                    ),
                ),
                ("Zeit", models.DateField(default=datetime.datetime.now)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
