# Generated by Django 4.2.4 on 2023-10-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0022_ausgeführter_befehl"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ausgeführter_befehl",
            options={"verbose_name_plural": "Ausgeführter Befehl"},
        ),
        migrations.AddField(
            model_name="ausgeführter_befehl",
            name="sequence_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
