# Generated by Django 4.2.4 on 2023-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0024_auftrag_sequence_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="auftrag",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
