# Generated by Django 4.2.4 on 2023-10-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0025_auftrag_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="ausgeführter_befehl",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
