# Generated by Django 4.2.4 on 2023-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0027_marketable_serial_number_modeltable_serial_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeltable",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
