# Generated by Django 4.2.4 on 2023-10-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0029_alter_modeltable_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeltable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
