# Generated by Django 4.2.4 on 2023-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0031_schadensarttable_marke"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auftrag",
            name="Schadensart",
            field=models.TextField(),
        ),
    ]
