# Generated by Django 4.2.4 on 2023-11-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0032_alter_auftrag_schadensart"),
    ]

    operations = [
        migrations.AddField(
            model_name="auftrag",
            name="Country",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="auftrag",
            name="State",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="auftrag",
            name="StreetName",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="auftrag",
            name="Adresszeile",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="auftrag",
            name="Hausnummer",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="auftrag",
            name="Stadt",
            field=models.CharField(default="", max_length=255),
        ),
    ]
