# Generated by Django 4.2.4 on 2023-11-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0033_auftrag_country_auftrag_state_auftrag_streetname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auftrag",
            name="Country",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auftrag",
            name="Hausnummer",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auftrag",
            name="Stadt",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auftrag",
            name="State",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auftrag",
            name="StreetName",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
