# Generated by Django 4.2.4 on 2023-12-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benutzer", "0034_alter_auftrag_country_alter_auftrag_hausnummer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auftrag",
            name="Postleitzahl",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
